clear; clc;
base_dir = fileparts(mfilename('fullpath'));
addpath(base_dir);
old_visible = get(0,'DefaultFigureVisible');
set(0,'DefaultFigureVisible','off');
cleanup = onCleanup(@() set(0,'DefaultFigureVisible',old_visible));
fprintf('smoke plan\n');
run(fullfile(base_dir,'solve_problem1.m'));
run(fullfile(base_dir,'solve_problem2.m'));
run(fullfile(base_dir,'solve_problem3.m'));
run(fullfile(base_dir,'solve_problem4.m'));
run(fullfile(base_dir,'solve_problem5.m'));
export_results();
validate_results();
convergence_check();
sensitivity_check();
solve_problem5_milp(.05);
run(fullfile(base_dir,'..','paper','make_figures.m'));
fprintf('done\n');
